python create_pngs.py mnist_test.bin mnist_test_png
python create_pngs.py mnist_train.bin mnist_train_png
python create_pngs.py mnist_background_images_test.bin mnist_background_images_test_png
python create_pngs.py mnist_background_images_train.bin mnist_background_images_train_png
